# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

**
!maintenance-automation/package.json
!maintenance-automation/package-lock.json
!maintenance-automation/tsconfig.json
!maintenance-automation/jest.config.js
!maintenance-automation/knip.json
!maintenance-automation/knip-production-plus-tests.json
!maintenance-automation/src/**
!superset-frontend/package.json
!superset-frontend/package-lock.json
!superset-frontend/src/**
!superset-frontend/packages/**
!superset-frontend/plugins/**
!superset-frontend/spec/**
!superset-frontend/storybook/**
!superset-frontend/types/**
!superset-frontend/webpack.config.js
!superset-frontend/tsconfig.json
!superset-frontend/knip.json
**/node_modules
**/dist
**/coverage
